---
title: "Progress"
author: "Marcelina Nagales"
date: "October 2, 2018"
output: html_document
---

## October 2, 2018

Initial progress is slow. I have something for each week (although some weeks are more developed than others). Currently working on Week 3 my texts
- Lewis Carroll texts

Done:
1. unnest_tokens(): make text into list of words
2. Tidy the works (perhaps before we unnest)
    - but this might just be for that specific library janeaustenr
3. data(stop_words), anti_join(stop_words): removes stop words from list 
4. count(word, sort = TRUE) : count words to store in list

Currently:
Count looks off, need to clean up (add custom stop_words)
Thinking about removing the math papers by Carroll
Also thinking about removing all chapter titles (?)
- will this effect the word frequency greatly?

## October 8, 2018

Need to finish current week work and then go backwards (if Future Experiments can also be completed before we play catch up that would be great too). 

Finally centered on my 2 corpus. Detective fiction and childrens literature. Specifically AA Milne and Arthur Conan Doyle vs Lewis Carroll and Frank L Baum

## October 10, 2018

From deciding on my final corpus (since I don't particularly have a corpus that I am interested in researching) and dowloading the required packages for the week, I'm resigned to finally set my corpus through the most convenient way possible. 

Giving myself time to mess up on the corpus will only make my final code working to the best of its ability. 
