---
title: "R Notebook"
output: html_notebook
---

Installed necessary packages within the terminal 
- quanteda
- 
```{r}
library(quanteda)
```

```{r}
my_corpus <- corpus(data_char_ukimmig2010)
summary(my_corpus)
```

```{r}
docvars(my_corpus, "Party") <- names(data_char_ukimmig2010)
docvars(my_corpus, "Year") <- 2010
summary(my_corpus)
```
Starting from here, the following commands will not run because I don't have these files in these specific folders
```{r}
require(readtext)

# text file
mytf3 <- readtext("~/Dropbox/QUANTESS/corpora/project_gutenberg/pg2701.txt", cache = FALSE)
summary(corpus(mytf3), 5)
```

```{r}
# multiple text files
mytf4 <- readtext("~/Dropbox/QUANTESS/corpora/inaugural/*.txt", cache = FALSE)
summary(corpus(mytf4), 5)
```

```{r}
# multiple text files with docvars from filenames
mytf5 <- readtext("~/Dropbox/QUANTESS/corpora/inaugural/*.txt", 
                  docvarsfrom = "filenames", sep = "-", docvarnames = c("Year", "President"))
summary(corpus(mytf5), 5)
```

```{r}
# XML data
mytf6 <- readtext("~/Dropbox/QUANTESS/quanteda_working_files/xmlData/plant_catalog.xml", 
                  textfield = "COMMON")
summary(corpus(mytf6), 5)
```

```{r}
# csv file
write.csv(data.frame(inaugSpeech = texts(data_corpus_inaugural), 
                     docvars(data_corpus_inaugural)),
          file = "/tmp/inaug_texts.csv", row.names = FALSE)
mytf7 <- readtext("/tmp/inaug_texts.csv", textfield = "inaugSpeech")
summary(corpus(mytf7), 5)
```
Ending here on the code that does not work on account of non existent files of non existent directories

```{r}
texts(data_corpus_inaugural)[2]
```

```{r}
summary(data_corpus_irishbudget2010)
```

```{r}
tokenInfo <- summary(data_corpus_inaugural)
if(require(ggplot2))
  ggplot(data=tokenInfo, aes(x=Year, y=Tokens, group = 1)) + geom_line() + geom_point() + scale_x_continuous(labels= c(seq(1789, 2017, 12)), breaks = seq(1789, 2017, 12)) + theme_bw()
```

```{r}
tokenInfo[which.max(tokenInfo$Tokens), ]
```

```{r}
my_corpus1 <- corpus(data_corpus_inaugural[1:5])
my_corpus2 <- corpus(data_corpus_inaugural[53:58])
my_corpus3 <- my_corpus1 + my_corpus2

summary(my_corpus3)

```

